### ISSUE TITLE
resolve test-related issue when running diffdock in container

### ISSUE THREAD

**Issue by NiklasTR** [labdao/diffdock#2]
this should be relatively easy to address

````
Precomputing and saving to cache SO(3) distribution table
Precomputing and saving to cache torus distribution table
100%|██████████| 201/201 [01:37<00:00,  2.07it/s]
100%|██████████| 201/201 [01:55<00:00,  1.75it/s]
/root/utils/torus.py:39: RuntimeWarning: invalid value encountered in divide
  score_ = grad(x, sigma[:, None], N=100) / p_
Reading molecules and generating local structures with RDKit (unless --keep_local_structures is turned on).
1it [00:00, 2113.00it/s]
Traceback (most recent call last):
  File "/opt/conda/envs/DiffDock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/DiffDock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/inference.py", line 81, in <module>
    test_dataset = PDBBind(transform=None, root='', protein_path_list=protein_path_list, ligand_descriptions=ligand_descriptions,
  File "/root/datasets/pdbbind.py", line 102, in __init__
    self.inference_preprocessing()
  File "/root/datasets/pdbbind.py", line 227, in inference_preprocessing
    if not os.path.exists(self.esm_embeddings_path): raise Exception('ESM embeddings path does not exist: ',self.esm_embeddings_path)
Exception: ('ESM embeddings path does not exist: ', 'data/esm2_output')
Failed to read molecule  /test/test.sdf  We are skipping it. The reason is the exception:  File error: Bad input file /test/test.sdf
Reading language model embeddings.
`````

**Comment by NiklasTR** [comment]
pushed a change to main that fixed the test path
