### ISSUE TITLE
resolve error when running current container on A100 GPU

### ISSUE THREAD

**Issue by NiklasTR** [labdao/diffdock#5]
while the CPU version is running without problems, when running the container on the system's GPU, I receive

```
Processing 1 of 1 batches (2 sequences)
Traceback (most recent call last):
  File "/opt/conda/envs/DiffDock/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/DiffDock/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/inference.py", line 16, in <module>
    from datasets.pdbbind import PDBBind
  File "/root/datasets/pdbbind.py", line 22, in <module>
    from utils.utils import read_strings_from_txt
  File "/root/utils/utils.py", line 12, in <module>
    from torch_geometric.nn.data_parallel import DataParallel
  File "/opt/conda/envs/DiffDock/lib/python3.9/site-packages/torch_geometric/nn/__init__.py", line 3, in <module>
    from .sequential import Sequential
  File "/opt/conda/envs/DiffDock/lib/python3.9/site-packages/torch_geometric/nn/sequential.py", line 8, in <module>
    from torch_geometric.nn.conv.utils.jit import class_from_module_repr
  File "/opt/conda/envs/DiffDock/lib/python3.9/site-packages/torch_geometric/nn/conv/__init__.py", line 25, in <module>
    from .spline_conv import SplineConv
  File "/opt/conda/envs/DiffDock/lib/python3.9/site-packages/torch_geometric/nn/conv/spline_conv.py", line 16, in <module>
    from torch_spline_conv import spline_basis, spline_weighting
  File "/opt/conda/envs/DiffDock/lib/python3.9/site-packages/torch_spline_conv/__init__.py", line 11, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'
````

My current best guess is to simplify the existing Dockerfile and rebuild the container.

**Comment by NiklasTR** [comment]
Summon an AWS P instance and run this
